id: project
name: Project
fields:
- name: title
  type: string
  required: true
- name: status
  type: enum
  enum_values:
  - active
  - on_hold
  - done
  required: true
- name: budget
  type: float
- name: owner
  type: string
