- id: customers
  type: entity
  target: customer
- id: products
  type: entity
  target: product
- id: invoices
  type: entity
  target: invoice
- id: subscriptions
  type: entity
  target: subscription
- id: payments
  type: entity
  target: payment
- id: checkouts
  type: entity
  target: checkout_session
